### ISSUE TITLE
ensure earthsea state is fully restored when midi devices are disconnected

### ISSUE THREAD

**Issue by ngwese** [monome/earthsea#6]
we should make sure that the grid (and earthsea app) state is fully refreshed when midi devices are disconnected. while experimenting i noticed that the recorded pattern light wasn't restored when the grid was plugged back in (but was unable to reproduce it).

**Comment by tehn** [comment]
i was able to swap between grid and midi without issues. but i will
continue to test.

**Comment by tehn** [comment]
or, perhaps i was doing this while a pattern was running, which would've
forced a refresh. but the refresh flag should be set on monome_connect()
anyway?

**Comment by tehn** [comment]
9652f01..9f0f790
